### ISSUE TITLE
Code used to train the VOC/COCO models

### ISSUE THREAD

**Issue by vipinpillai** [facebookresearch/TorchRay#6]
Thanks for making the benchmark code available. 

Would it be possible to share the code that was used to train the VOC/COCO models as well?

@ruthcfong

**Comment by ruthcfong** [comment]
Thanks for your question @vipinpillai.

For context, the models were originally trained in caffe by Jianming Zhang (@jimmie33) for their ECCV 2016 Excitation Backprop paper. We worked with Jianming as well as Vitali Petsiuk (@eclique) and Abir Das, who converted Jianming's models to PyTorch for their BMVC 2018 RISE paper.

I'd recommend reaching out to Jianming if you'd like the training scripts. Hope that helps.

**Comment by vipinpillai** [comment]
Thanks @ruthcfong! I'll reach out to Jianming/Vitali.
